#!bash

alias docko=docker-compose
alias docko-run='docko run --rm server'
alias docko-debug='docko-run --rm --service-ports server'

function ___docko-psql {
  docko exec db psql postgres -U postgres
}

alias docko-psql='___docko-psql'

function ___docko-house {
  docko exec db psql house_locator -U postgres
}

alias docko-house-db='___docko-house'

function ___docko-restart-tail {
  docko restart && docko logs -f --tail=100
}

alias docko-restart-tail='___docko-restart-tail'
