#!bash

alias docko=docker-compose
alias docko-run='docko run --rm server'
alias docko-debug='docko-run --rm --service-ports server'

function ___docko-psql {
  docko exec db psql postgres -U postgres
}

alias docko-psql='___docko-psql'
